export declare const GAME_WIDTH = 948;
export declare const GAME_HEIGHT = 533;
export declare const HUD_WIDTH = 128;
export declare const PLAY_AREA_WIDTH: number;
export declare const PLAY_AREA_HEIGHT = 533;
export declare const WORLD_LIMIT_X = 1600;
export declare const FILLMAP_WIDTH = 64;
export declare const OREMAP_WIDTH: number;
export declare const FILLMAP_HEIGHT = 96;
export declare const OREMAP_HEIGHT: number;
export declare const DEBUG_TILE_POSITIONS = false;
