import { Entity } from "./entity.js";
import { Pickup } from "./pickup.js";
import { OreType } from "./tilemap.js";
export declare class Sub extends Entity {
    x: number;
    y: number;
    dx: number;
    dy: number;
    facing: number;
    rotation: number;
    oxygen: number;
    oxygenTanks: number;
    fuel: number;
    fuelTanks: number;
    invulnerable: boolean;
    invulnerableTime: number;
    mining: boolean;
    miningTime: number;
    miningFillX: number;
    miningFillY: number;
    miningSpeed: number;
    inventory: OreType[];
    inventorySize: number;
    inventoryPickups: Pickup[];
    menu: 'none' | 'shop' | 'pause';
    moveSoundCallback: (() => void) | null;
    miningSoundCallback: (() => void) | null;
    reset(): void;
    update(dt: number): void;
    render(ctx: CanvasRenderingContext2D): void;
    renderLights(ctx: OffscreenCanvasRenderingContext2D): void;
    hit(dmg: number): void;
}
export declare const sub: Sub;
